sudo: required
services:
 - docker

scripts:
  - docker build -t rajkotti/node .
  - docker images rajkotti/node

before_deploy:
  - docker login rajkotti --password-stdin

deploy:
  provider: script 
  script: docker push rajkotti/node
  on:
    branch: master 